### ISSUE TITLE
Data preparation scripts

### ISSUE THREAD

**Issue by Mohinta2892** [jakobtroidl/neuron-shape-reasoning#1]
Hi Jakob,

Amazing work!

I am wondering if you could share the data preparation scripts (sampling from skeletons and augmentation) used for your datasets?

Best,
Samia

**Comment by jakobtroidl** [comment]
Hi @Mohinta2892, thanks for your interest in our work. All code for data sampling and augmentation is already in the repository. This is all done in the `MultiNeuronDataset` class, see [here](https://github.com/jakobtroidl/neuron-shape-reasoning/blob/dd6cf751eb856e9d7b9ffb44064045ed095c67b0/src/datasets.py#L152). Feel free to let me know if you have more questions.

**Comment by Mohinta2892** [comment]
Many thanks Jakob, I was not sure if `datasets.py` was the one to look at. Thanks for confirming.
